import streamlit as st
import torch
from diffusers import StableDiffusionPipeline

st.set_page_config(
    page_title="DreamCanvas",
    page_icon="🎨",
    layout="centered"
)

st.title("🎨 DreamCanvas")
st.write("Free AI Text-to-Image Generator")

prompt = st.text_area(
    "Enter your image prompt:",
    placeholder="Example: A futuristic city at sunset with flying cars"
)

if st.button("✨ Generate Image"):

    if not prompt.strip():
        st.warning("Please enter the prompt first.")

    else:
        try:
            with st.spinner("Loading AI model and generating image..."):

                pipe = StableDiffusionPipeline.from_pretrained(
                    "stable-diffusion-v1-5/stable-diffusion-v1-5",
                    use_safetensors=True
                )

                pipe = pipe.to("cpu")

                image = pipe(
                    prompt,
                    num_inference_steps=20,
                    height=512,
                    width=512
                ).images[0]

                st.image(
                    image,
                    caption="Generated by DreamCanvas"
                )

        except Exception as e:
            st.error(f"Error: {e}")